import sqlite3

from models.postgres_migracion import (
    ResultadoValidacionPostgres,
    _definicion_tabla,
    _indices_unicos,
    _normalizar_fila_origen,
    _tipo_postgres,
)


def test_tipo_postgres_convierte_tipos_sqlite_habituales():
    assert _tipo_postgres("INTEGER") == "INTEGER"
    assert _tipo_postgres("REAL") == "DOUBLE PRECISION"
    assert _tipo_postgres("BLOB") == "BYTEA"
    assert _tipo_postgres("TEXT") == "TEXT"


def test_definicion_tabla_preserva_clave_y_autoincremento():
    conn = sqlite3.connect(":memory:")
    conn.execute(
        "CREATE TABLE ejemplo (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL, activo INTEGER DEFAULT 1)"
    )
    ddl, columnas, pk = _definicion_tabla(conn, "ejemplo")

    assert '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY' in ddl
    assert '"nombre" TEXT NOT NULL' in ddl
    assert 'PRIMARY KEY ("id")' in ddl
    assert columnas == ["id", "nombre", "activo"]
    assert pk == ["id"]


def test_normalizar_fila_convierte_vacios_numericos_a_null():
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute("CREATE TABLE ejemplo (numero INTEGER, importe REAL, texto TEXT)")
    conn.execute("INSERT INTO ejemplo VALUES ('', '', '')")
    fila = conn.execute("SELECT * FROM ejemplo").fetchone()

    assert _normalizar_fila_origen(fila, {"numero": "INTEGER", "importe": "REAL", "texto": "TEXT"}) == (
        None,
        None,
        "",
    )


def test_normalizar_fila_elimina_nul_de_texto():
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute("CREATE TABLE ejemplo (texto TEXT)")
    conn.execute("INSERT INTO ejemplo VALUES (?)", ("OCR\x00con\x00ruido",))
    fila = conn.execute("SELECT * FROM ejemplo").fetchone()

    assert _normalizar_fila_origen(fila, {"texto": "TEXT"}) == ("OCRconruido",)


def test_resultado_validacion_identifica_solo_diferencias():
    resultado = ResultadoValidacionPostgres({"ok": (2, 2), "error": (3, 2)})
    assert resultado.diferencias == {"error": (3, 2)}


def test_indices_unicos_conservan_condicion_where():
    conn = sqlite3.connect(":memory:")
    conn.execute("CREATE TABLE mensajes (id INTEGER PRIMARY KEY, graph_id TEXT)")
    conn.execute(
        "CREATE UNIQUE INDEX idx_graph ON mensajes(graph_id) "
        "WHERE graph_id IS NOT NULL AND graph_id<>''"
    )

    assert list(_indices_unicos(conn, "mensajes")) == [
        ("idx_graph", ["graph_id"], "graph_id IS NOT NULL AND graph_id<>''")
    ]
