from models.gestor_postgres import (
    ConexionPostgres,
    CursorPostgres,
    FilaPostgres,
    GestorPostgres,
    adaptar_sql_a_postgres,
    crear_dsn_postgres,
)


def test_adaptar_sql_a_postgres_convierte_marcadores_e_ignore():
    sql = "INSERT OR IGNORE INTO tabla (id, nombre) VALUES (?, ?)"
    assert adaptar_sql_a_postgres(sql) == (
        "INSERT INTO tabla (id, nombre) VALUES (%s, %s) ON CONFLICT DO NOTHING"
    )


def test_traducir_insert_replace_plan_cuentas_usa_clave_compuesta():
    sql = (
        "INSERT OR REPLACE INTO plan_cuentas "
        "(codigo_empresa, ejercicio, cuenta, descripcion) VALUES (?, ?, ?, ?)"
    )
    traducido = adaptar_sql_a_postgres(sql)

    assert "ON CONFLICT (codigo_empresa, ejercicio, cuenta)" in traducido
    assert "descripcion=EXCLUDED.descripcion" in traducido
    assert "codigo_empresa=EXCLUDED.codigo_empresa" not in traducido


def test_fila_postgres_admite_indices_y_claves():
    fila = FilaPostgres({"id": 7, "nombre": "Gestinem"})
    assert fila[0] == 7
    assert fila["nombre"] == "Gestinem"


def test_adaptar_sql_a_postgres_deja_ddl_postgres_sin_cambios():
    sql = "CREATE TABLE IF NOT EXISTS usuarios_permisos_globales (id INTEGER PRIMARY KEY)"
    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in adaptar_sql_a_postgres(sql)


def test_cursor_postgres_description_es_compatible():
    class Columna:
        name = "codigo"

    class Cursor:
        description = [Columna()]
        rowcount = 3

    cursor = CursorPostgres(Cursor())
    assert cursor.description[0][0] == "codigo"
    assert cursor.rowcount == 3


def test_crear_dsn_postgres_escapa_password_especial():
    dsn = crear_dsn_postgres(
        host="192.168.0.19",
        port="5432",
        database="gest2a3eco",
        user="gest2a3eco",
        password="clave con ' comilla",
    )

    assert "host=192.168.0.19" in dsn
    assert "password='clave con \\' comilla'" in dsn


class _Resultado:
    def __init__(self, row=None, rows=None):
        self._row = row
        self._rows = list(rows or [])

    def fetchone(self):
        return self._row

    def fetchall(self):
        return self._rows


class _ConexionFalsa:
    def __init__(self, secuencia=None, currval=None):
        self.secuencia = secuencia
        self.currval = currval
        self.rollback_count = 0
        self.commit_count = 0
        self.closed = False
        self.sentencias = []

    def execute(self, sql, params=None):
        if "pg_get_serial_sequence" in sql:
            return _Resultado({"pg_get_serial_sequence": self.secuencia})
        if "currval" in sql:
            return _Resultado({"currval": self.currval})
        raise AssertionError(sql)

    def rollback(self):
        self.rollback_count += 1

    def commit(self):
        self.commit_count += 1

    def close(self):
        self.closed = True

    def cursor(self):
        return _CursorFalso(self)


class _CursorFalso:
    description = []

    def __init__(self, conexion, *, error=None):
        self.connection = conexion
        self.rowcount = 1
        self.error = error

    def execute(self, sql, params=None):
        if self.error:
            raise self.error
        self.connection.sentencias.append((sql, params))


def test_cursor_insert_textual_no_aborta_por_lastrowid():
    conexion = _ConexionFalsa(secuencia=None)
    cursor = CursorPostgres(_CursorFalso(conexion))

    cursor.execute("INSERT INTO terceros (id, nombre) VALUES (%s, %s)", ("t1", "Tercero"))

    assert cursor.lastrowid is None
    assert conexion.rollback_count == 0


def test_cursor_insert_identity_recupera_lastrowid():
    conexion = _ConexionFalsa(secuencia="public.usuarios_id_seq", currval=42)
    cursor = CursorPostgres(_CursorFalso(conexion))

    cursor.execute("INSERT INTO usuarios (nombre) VALUES (%s)", ("Usuario",))

    assert cursor.lastrowid == 42


def test_cursor_error_hace_rollback_para_recuperar_conexion():
    conexion = _ConexionFalsa()
    cursor = CursorPostgres(_CursorFalso(conexion, error=RuntimeError("sql incorrecto")))

    try:
        cursor.execute("SELECT columna_inexistente FROM tabla")
    except RuntimeError:
        pass
    else:
        raise AssertionError("Se esperaba RuntimeError")

    assert conexion.rollback_count == 1


def test_conexion_postgres_context_manager_confirma_o_deshace():
    correcta = _ConexionFalsa()
    with ConexionPostgres(correcta):
        pass
    assert correcta.commit_count == 1

    fallida = _ConexionFalsa()
    try:
        with ConexionPostgres(fallida):
            raise ValueError("fallo")
    except ValueError:
        pass
    assert fallida.rollback_count == 1


def test_upsert_banco_confirma_plantilla_sin_columna_id():
    conexion = _ConexionFalsa(secuencia=None)
    gestor = object.__new__(GestorPostgres)
    gestor.conn = ConexionPostgres(conexion)
    plantilla = {
        "codigo_empresa": "E00193",
        "ejercicio": 2026,
        "banco": "Banco prueba",
        "numero_cuenta": "ES00",
        "subcuenta_banco": "57200001",
        "subcuenta_por_defecto": "55500000",
        "conceptos": [{"patron": "RECIBO*", "subcuenta": "41000001"}],
        "excel": {"primera_fila_procesar": 3, "columnas": {"Importe": "F"}},
    }

    gestor.upsert_banco(plantilla)

    assert conexion.rollback_count == 0
    assert conexion.commit_count == 1
    insert_sql, params = conexion.sentencias[0]
    assert "ON CONFLICT(codigo_empresa, ejercicio, banco)" in insert_sql
    assert params[0:6] == (
        "E00193", 2026, "Banco prueba", "ES00", "57200001", "55500000"
    )
    assert '"primera_fila_procesar": 3' in params[7]


def test_upsert_factura_emitida_con_id_textual_confirma_transaccion():
    conexion = _ConexionFalsa(secuencia=None)
    gestor = object.__new__(GestorPostgres)
    gestor.conn = ConexionPostgres(conexion)
    factura = {
        "id": "factura-empleado-809",
        "codigo_empresa": "E00809",
        "ejercicio": 2026,
        "serie": "A",
        "numero": "000009",
        "fecha_asiento": "30/07/2026",
        "nombre": "Cliente prueba",
        "borrador": 0,
        "lineas": [],
    }

    fid = gestor.upsert_factura_emitida(factura)

    assert fid == "factura-empleado-809"
    assert conexion.rollback_count == 0
    assert conexion.commit_count == 1
    insert_sql, params = conexion.sentencias[0]
    assert "INSERT INTO facturas_emitidas_docs" in insert_sql
    assert "ON CONFLICT(id) DO UPDATE" in insert_sql
    assert params[0:3] == ("factura-empleado-809", "E00809", 2026)


class _ConexionMigracionesFalsa:
    def __init__(
        self,
        columnas,
        *,
        tabla_permisos=True,
        indice_permisos=True,
        tabla_dgt_facturas=True,
        indice_dgt_facturas=True,
        tabla_avisos_correo=True,
        tabla_avisos_vistos=True,
        tabla_categorias_documentales=True,
        tabla_documentos_archivo=True,
        tabla_decisiones_adjuntos=True,
        tabla_firma_solicitudes=True,
        indice_firma_solicitudes=True,
        tabla_firma_firmantes=True,
        tabla_firma_zonas=True,
        tabla_firma_eventos=True,
        tabla_ocr_aprendizaje=True,
        indice_ocr_aprendizaje=True,
    ):
        self.columnas = columnas
        self.tabla_permisos = tabla_permisos
        self.indice_permisos = indice_permisos
        self.tabla_dgt_facturas = tabla_dgt_facturas
        self.indice_dgt_facturas = indice_dgt_facturas
        self.tabla_avisos_correo = tabla_avisos_correo
        self.tabla_avisos_vistos = tabla_avisos_vistos
        self.tabla_categorias_documentales = tabla_categorias_documentales
        self.tabla_documentos_archivo = tabla_documentos_archivo
        self.tabla_decisiones_adjuntos = tabla_decisiones_adjuntos
        self.tabla_firma_solicitudes = tabla_firma_solicitudes
        self.indice_firma_solicitudes = indice_firma_solicitudes
        self.tabla_firma_firmantes = tabla_firma_firmantes
        self.tabla_firma_zonas = tabla_firma_zonas
        self.tabla_firma_eventos = tabla_firma_eventos
        self.tabla_ocr_aprendizaje = tabla_ocr_aprendizaje
        self.indice_ocr_aprendizaje = indice_ocr_aprendizaje
        self.sentencias = []
        self.commit_count = 0

    def execute(self, sql, params=None):
        self.sentencias.append((sql, params))
        if "information_schema.columns" in sql:
            return _Resultado(rows=[
                {"table_name": tabla, "column_name": columna}
                for tabla, columna in self.columnas
            ])
        if "AS tabla_permisos" in sql:
            return _Resultado({
                "tabla_permisos": (
                    "usuarios_permisos_globales" if self.tabla_permisos else None
                ),
                "indice_permisos": (
                    "idx_usuarios_permisos_globales_usuario"
                    if self.indice_permisos else None
                ),
                "tabla_dgt_facturas": (
                    "dgt_facturas" if self.tabla_dgt_facturas else None
                ),
                "indice_dgt_facturas": (
                    "idx_dgt_facturas_factura"
                    if self.indice_dgt_facturas else None
                ),
                "tabla_avisos_correo": (
                    "comunicaciones_avisos_estado"
                    if self.tabla_avisos_correo else None
                ),
                "tabla_avisos_vistos": (
                    "comunicaciones_avisos_vistos"
                    if self.tabla_avisos_vistos else None
                ),
                "tabla_categorias_documentales": (
                    "categorias_documentales"
                    if self.tabla_categorias_documentales else None
                ),
                "tabla_documentos_archivo": (
                    "documentos_archivo" if self.tabla_documentos_archivo else None
                ),
                "tabla_decisiones_adjuntos": (
                    "comunicaciones_adjuntos_decisiones"
                    if self.tabla_decisiones_adjuntos else None
                ),
                "tabla_firma_solicitudes": (
                    "firma_solicitudes" if self.tabla_firma_solicitudes else None
                ),
                "indice_firma_solicitudes": (
                    "idx_firma_solicitudes_empresa"
                    if self.indice_firma_solicitudes else None
                ),
                "tabla_firma_firmantes": (
                    "firma_firmantes" if self.tabla_firma_firmantes else None
                ),
                "tabla_firma_zonas": "firma_zonas" if self.tabla_firma_zonas else None,
                "tabla_firma_eventos": (
                    "firma_eventos" if self.tabla_firma_eventos else None
                ),
                "tabla_ocr_aprendizaje": (
                    "ocr_aprendizaje_ejemplos"
                    if self.tabla_ocr_aprendizaje else None
                ),
                "indice_ocr_aprendizaje": (
                    "idx_ocr_aprendizaje_empresa"
                    if self.indice_ocr_aprendizaje else None
                ),
            })
        return _Resultado()

    def commit(self):
        self.commit_count += 1


_COLUMNAS_ESENCIALES = {
    ("empresas", "cuenta_bancaria"),
    ("empresas", "cuentas_bancarias"),
    ("empresas", "pdf_ref_seq"),
    ("empresas", "serie_emitidas_rect"),
    ("empresas", "siguiente_num_emitidas_rect"),
    ("empresas", "logo_max_width_mm"),
    ("empresas", "logo_max_height_mm"),
    ("empresas", "pais"),
    ("empresas", "naf"),
    ("empresas", "responsable"),
    ("empresas", "activo"),
    ("usuarios", "must_change_password"),
    ("comunicaciones", "etiqueta"),
    ("comunicaciones_mensajes", "tiene_adjuntos"),
    ("comunicaciones_sin_asignar", "etiqueta"),
    ("facturas_recibidas_ocr", "tipo_operacion_iva"),
    ("firma_solicitudes", "documento_firmado_archivo_id"),
    ("ocr_aprendizaje_ejemplos", "marcas_json"),
    ("facturas_emitidas_docs", "updated_at"),
    ("facturas_emitidas_docs", "pdf_generated_at"),
}


def test_migraciones_postgres_no_ejecutan_ddl_si_esquema_esta_actualizado():
    conexion = _ConexionMigracionesFalsa(_COLUMNAS_ESENCIALES)
    gestor = object.__new__(GestorPostgres)
    gestor.conn = conexion

    gestor._aplicar_migraciones_esenciales_postgres()

    sql = "\n".join(sentencia for sentencia, _params in conexion.sentencias)
    assert "ALTER TABLE" not in sql
    assert "CREATE TABLE" not in sql
    assert "CREATE INDEX" not in sql
    assert conexion.commit_count == 1


def test_migraciones_postgres_crean_solo_elementos_que_faltan():
    columnas = _COLUMNAS_ESENCIALES - {("empresas", "responsable")}
    conexion = _ConexionMigracionesFalsa(
        columnas, tabla_permisos=False, indice_permisos=False
    )
    gestor = object.__new__(GestorPostgres)
    gestor.conn = conexion

    gestor._aplicar_migraciones_esenciales_postgres()

    ddl = [
        " ".join(sentencia.split())
        for sentencia, _params in conexion.sentencias
        if sentencia.lstrip().upper().startswith(("ALTER", "CREATE"))
    ]
    assert len(ddl) == 3
    assert ddl[0] == (
        "ALTER TABLE empresas ADD COLUMN IF NOT EXISTS responsable TEXT"
    )
    assert ddl[1].startswith(
        "CREATE TABLE IF NOT EXISTS usuarios_permisos_globales"
    )
    assert ddl[2].startswith(
        "CREATE INDEX IF NOT EXISTS idx_usuarios_permisos_globales_usuario"
    )
    assert conexion.commit_count == 1


def test_fila_postgres_es_compatible_con_iteracion_por_valores():
    fila = FilaPostgres(
        nombre_archivo="factura.pdf",
        motor_ocr="azure",
        estado="pendiente_revision",
    )
    columnas = ["nombre_archivo", "motor_ocr", "estado"]

    assert dict(zip(columnas, fila)) == {
        "nombre_archivo": "factura.pdf",
        "motor_ocr": "azure",
        "estado": "pendiente_revision",
    }
    assert fila[0] == "factura.pdf"
    assert dict(fila)["motor_ocr"] == "azure"
