// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ3EPhHEtySopdHnVW3oDI4ELYo9GDCa4',
    appId: '1:268163516548:web:3045f4ccec08b0eafddad1',
    messagingSenderId: '268163516548',
    projectId: 'gest2a3eco',
    authDomain: 'gest2a3eco.firebaseapp.com',
    storageBucket: 'gest2a3eco.firebasestorage.app',
    measurementId: 'G-J911ZEJ2XX',
  );
}
