FACTURAE_NS = "http://www.facturae.es/Facturae/2009/v3.2.2/Facturae"
DS_NS = "http://www.w3.org/2000/09/xmldsig#"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
SCHEMA_LOCATION = "http://www.facturae.es/Facturae/2009/v3.2.2/Facturae facturae_3_2_2.xsd"

SCHEMA_VERSION = "3.2.2"
MODALITY_INDIVIDUAL = "I"
INVOICE_ISSUER_TYPE = "EM"
INVOICE_DOCUMENT_TYPE = "FC"
INVOICE_CLASS_ORIGINAL = "OO"
INVOICE_CLASS_CORRECTIVE = "OR"

TAX_TYPE_VAT = "01"
TAX_TYPE_IRPF = "04"

UNIT_OF_MEASURE_UNITS = "01"

ADMIN_CENTRE_ROLE_OFFICE = "01"
ADMIN_CENTRE_ROLE_MANAGER = "02"
ADMIN_CENTRE_ROLE_PROCESSING = "03"
ADMIN_CENTRE_ROLE_PROPONENT = "04"

FACTURAE_STATUS_NO_GENERADO = "no_generado"
FACTURAE_STATUS_GENERADO = "generado"
FACTURAE_STATUS_ERROR_VALIDACION = "error_validacion"
FACTURAE_STATUS_FIRMADO = "firmado"
FACTURAE_STATUS_PRESENTADO = "presentado"
