"""Gestor PostgreSQL de la aplicacion."""

from __future__ import annotations

import re
from collections.abc import Iterable

from models.gestor_base import AUTH_SCHEMA, SCHEMA, GestorBase


class DatabasePostgresError(RuntimeError):
    pass


def crear_dsn_postgres(host: str, port: int | str, database: str, user: str, password: str) -> str:
    """Crea una cadena de conexion escapando credenciales de forma segura."""
    try:
        from psycopg.conninfo import make_conninfo
    except ImportError as exc:
        raise DatabasePostgresError(
            "Falta la dependencia psycopg para conectar con PostgreSQL."
        ) from exc
    return make_conninfo(
        host=str(host or "").strip(),
        port=int(port),
        dbname=str(database or "").strip(),
        user=str(user or "").strip(),
        password=str(password or ""),
        connect_timeout=5,
    )


class FilaPostgres(dict):
    """Fila de resultado: admite clave de texto e indice numerico."""

    def __getitem__(self, key):
        if isinstance(key, int):
            return tuple(self.values())[key]
        return super().__getitem__(key)

    def __iter__(self):
        """Itera por valores para conservar contratos historicos del gestor."""
        return iter(self.values())


def _adaptar_fila(row):
    return None if row is None else FilaPostgres(row)


def _traducir_insert_replace(sql: str) -> str:
    patron = re.compile(
        r"^\s*INSERT\s+OR\s+REPLACE\s+INTO\s+([\w\"]+)\s*\(([^)]+)\)\s*(VALUES\s*\(.+\))\s*;?\s*$",
        re.IGNORECASE | re.DOTALL,
    )
    match = patron.match(sql)
    if not match:
        return sql
    tabla, columnas, valores = match.groups()
    nombres = [columna.strip() for columna in columnas.split(",")]
    tabla_normalizada = tabla.strip('"').lower()
    claves_por_tabla = {
        "plan_cuentas": ("codigo_empresa", "ejercicio", "cuenta"),
    }
    claves = claves_por_tabla.get(tabla_normalizada)
    if not claves:
        # No se debe inventar una restriccion: mantener la instruccion para que
        # el error identifique cualquier caso SQL nuevo que deba adaptarse.
        return sql
    claves_norm = {clave.lower() for clave in claves}
    actualizables = [nombre for nombre in nombres if nombre.strip('"').lower() not in claves_norm]
    actualizaciones = ", ".join(
        f"{nombre}=EXCLUDED.{nombre}" for nombre in actualizables
    )
    conflicto = ", ".join(claves)
    return (
        f"INSERT INTO {tabla} ({columnas}) {valores} "
        f"ON CONFLICT ({conflicto}) DO UPDATE SET {actualizaciones}"
    )


def adaptar_sql_a_postgres(sql: str) -> str:
    """Adapta el SQL historico de la capa de datos al dialecto PostgreSQL."""
    traducido = str(sql)
    traducido = _traducir_insert_replace(traducido)
    if re.match(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", traducido, re.IGNORECASE):
        traducido = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", traducido, count=1, flags=re.IGNORECASE)
        traducido = traducido.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    traducido = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        traducido,
        flags=re.IGNORECASE,
    )
    traducido = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        traducido,
        flags=re.IGNORECASE,
    )
    traducido = re.sub(r"\bREAL\b", "DOUBLE PRECISION", traducido, flags=re.IGNORECASE)
    return traducido.replace("?", "%s")


def _parse_pragma_table_info(sql: str) -> str:
    match = re.match(r"^\s*PRAGMA\s+table_info\s*\(\s*['\"]?([\w]+)['\"]?\s*\)\s*;?\s*$", str(sql), re.IGNORECASE)
    return match.group(1).lower() if match else ""


def _split_sql_script(script: str) -> list[str]:
    sentencias: list[str] = []
    actual: list[str] = []
    quote = ""
    escape = False
    for char in str(script or ""):
        actual.append(char)
        if escape:
            escape = False
            continue
        if char == "\\" and quote:
            escape = True
            continue
        if char in ("'", '"'):
            quote = "" if quote == char else (char if not quote else quote)
            continue
        if char == ";" and not quote:
            sentencia = "".join(actual).strip().rstrip(";").strip()
            if sentencia:
                sentencias.append(sentencia)
            actual = []
    resto = "".join(actual).strip()
    if resto:
        sentencias.append(resto)
    return sentencias


class CursorPostgres:
    def __init__(self, cursor):
        self._cursor = cursor
        self.lastrowid = None

    def execute(self, sql: str, params=None):
        traducido = adaptar_sql_a_postgres(sql)
        try:
            self._cursor.execute(traducido, params)
            if (
                self._cursor.rowcount != 0
                and re.match(r"^\s*INSERT\b", traducido, re.IGNORECASE)
                and " RETURNING " not in traducido.upper()
            ):
                self._cargar_lastrowid(traducido)
        except Exception:
            # PostgreSQL deja la transaccion en error tras una sentencia fallida:
            # hay que deshacerla para que una vista que captura el error no
            # rompa las siguientes operaciones.
            self._cursor.connection.rollback()
            raise
        return self

    def executemany(self, sql: str, params_seq: Iterable):
        try:
            self._cursor.executemany(adaptar_sql_a_postgres(sql), params_seq)
        except Exception:
            self._cursor.connection.rollback()
            raise
        return self

    def _cargar_lastrowid(self, sql: str) -> None:
        """Obtiene el ID solo si la tabla tiene una secuencia en ``id``.

        ``SELECT LASTVAL()`` falla cuando el INSERT usa una clave textual y
        aborta toda la transaccion. ``pg_get_serial_sequence`` permite
        comprobarlo sin provocar ese fallo.
        """
        self.lastrowid = None
        match = re.match(
            r'^\s*INSERT\s+INTO\s+("?[\w]+"?)',
            sql,
            flags=re.IGNORECASE,
        )
        if not match:
            return
        tabla = match.group(1).strip('"')
        row = self._cursor.connection.execute(
            """
            SELECT pg_get_serial_sequence(%s, 'id')
            FROM pg_attribute
            WHERE attrelid=to_regclass(%s)
              AND attname='id'
              AND NOT attisdropped
            """,
            (tabla, tabla),
        ).fetchone()
        secuencia = next(iter(row.values())) if isinstance(row, dict) and row else (row[0] if row else None)
        if not secuencia:
            return
        row = self._cursor.connection.execute(
            "SELECT currval(%s::regclass)",
            (secuencia,),
        ).fetchone()
        self.lastrowid = next(iter(row.values())) if isinstance(row, dict) else row[0]

    def fetchone(self):
        return _adaptar_fila(self._cursor.fetchone())

    def fetchall(self):
        return [_adaptar_fila(row) for row in self._cursor.fetchall()]

    def fetchmany(self, size=None):
        rows = self._cursor.fetchmany(size) if size is not None else self._cursor.fetchmany()
        return [_adaptar_fila(row) for row in rows]

    @property
    def description(self):
        """Metadatos normalizados a tuplas para contratos historicos."""
        descripcion = self._cursor.description or []
        return [(col.name, None, None, None, None, None, None) for col in descripcion]

    @property
    def rowcount(self):
        """Numero de filas afectadas."""
        return self._cursor.rowcount

    def __iter__(self):
        return (_adaptar_fila(row) for row in self._cursor)

    def close(self):
        self._cursor.close()


class ConexionPostgres:
    def __init__(self, conexion):
        self._conexion = conexion

    def execute(self, sql: str, params=None):
        pragma = _parse_pragma_table_info(sql)
        if pragma:
            sql = """
                SELECT
                  ordinal_position - 1 AS cid,
                  column_name AS name,
                  data_type AS type,
                  CASE WHEN is_nullable='NO' THEN 1 ELSE 0 END AS notnull,
                  column_default AS dflt_value,
                  0 AS pk
                FROM information_schema.columns
                WHERE table_schema=current_schema()
                  AND table_name=%s
                ORDER BY ordinal_position
            """
            params = (pragma,)
        cursor = CursorPostgres(self._conexion.cursor())
        return cursor.execute(sql, params)

    def executemany(self, sql: str, params_seq: Iterable):
        cursor = CursorPostgres(self._conexion.cursor())
        return cursor.executemany(sql, params_seq)

    def executescript(self, script: str):
        for sentencia in _split_sql_script(script):
            self.execute(sentencia)
        return self

    def commit(self):
        self._conexion.commit()

    def rollback(self):
        self._conexion.rollback()

    def close(self):
        self._conexion.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        return False


class GestorPostgres(GestorBase):
    """Implementacion PostgreSQL de la API publica del gestor de datos.

    Hereda temporalmente metodos de negocio ya existentes. La conexion adapta
    marcadores, filas y las variantes SQL historicas utilizadas por la
    aplicacion, pero la base operativa es siempre PostgreSQL.
    """

    def __init__(self, dsn: str):
        self.dsn = str(dsn or "").strip()
        self.data_source = "PostgreSQL"
        if not self.dsn:
            raise DatabasePostgresError("No se ha configurado la conexion PostgreSQL.")
        try:
            import psycopg
            from psycopg.rows import dict_row

            conexion = psycopg.connect(self.dsn, row_factory=dict_row)
            self.conn = ConexionPostgres(conexion)
            existe = self.conn.execute("SELECT to_regclass('public.empresas')").fetchone()[0]
            if not existe:
                self._inicializar_esquema_postgres()
            self._aplicar_migraciones_esenciales_postgres()
        except DatabasePostgresError:
            raise
        except Exception as exc:
            raise DatabasePostgresError(f"No se pudo abrir PostgreSQL: {exc}") from exc

    def _inicializar_esquema_postgres(self) -> None:
        """Crea el esquema base en una base PostgreSQL vacia."""
        self.conn.executescript(SCHEMA + AUTH_SCHEMA)
        self.conn.commit()
        self._migrate_terceros_global()
        self._migrate_maestro_subcuentas()
        self._migrate_notificaciones()
        self._migrate_seguridad_social()
        self._migrate_prefijo_ingreso_empresa()
        self.conn.commit()

    def _aplicar_migraciones_esenciales_postgres(self) -> None:
        """Crea elementos de seguridad y modulos añadidos tras el esquema base.

        PostgreSQL debe quedar listo para autenticar desde el primer arranque.

        Se consulta primero el catalogo porque incluso ``ALTER TABLE ... IF
        NOT EXISTS`` solicita un bloqueo exclusivo. Con otros puestos abiertos
        ese bloqueo podia retrasar el login aunque el esquema ya estuviera al
        dia.
        """
        self._asegurar_esquema_plantillas_firma()
        self._asegurar_esquema_mensajeria_local()
        columnas = (
            ("empresas", "cuenta_bancaria", "TEXT"),
            ("empresas", "cuentas_bancarias", "TEXT"),
            ("empresas", "pdf_ref_seq", "INTEGER"),
            ("empresas", "serie_emitidas_rect", "TEXT"),
            ("empresas", "siguiente_num_emitidas_rect", "INTEGER"),
            ("empresas", "logo_max_width_mm", "DOUBLE PRECISION"),
            ("empresas", "logo_max_height_mm", "DOUBLE PRECISION"),
            ("empresas", "pais", "TEXT"),
            ("empresas", "naf", "TEXT"),
            ("empresas", "responsable", "TEXT"),
            ("empresas", "activo", "INTEGER"),
            ("usuarios", "must_change_password", "INTEGER NOT NULL DEFAULT 0"),
            ("comunicaciones", "etiqueta", "TEXT"),
            ("comunicaciones_mensajes", "tiene_adjuntos", "INTEGER NOT NULL DEFAULT 0"),
            ("comunicaciones_sin_asignar", "etiqueta", "TEXT"),
            ("facturas_recibidas_ocr", "tipo_operacion_iva", "TEXT"),
            ("ocr_aprendizaje_ejemplos", "marcas_json", "TEXT NOT NULL DEFAULT '{}'"),
            ("facturas_emitidas_docs", "updated_at", "TEXT"),
            ("facturas_emitidas_docs", "pdf_generated_at", "TEXT"),
            ("firma_solicitudes", "documento_firmado_archivo_id", "TEXT"),
        )
        existentes = {
            (str(row["table_name"]), str(row["column_name"]))
            for row in self.conn.execute(
                """
                SELECT table_name, column_name
                FROM information_schema.columns
                WHERE table_schema=current_schema()
                  AND table_name IN (
                    'empresas', 'usuarios', 'comunicaciones', 'comunicaciones_mensajes',
                    'comunicaciones_sin_asignar', 'facturas_recibidas_ocr'
                    , 'ocr_aprendizaje_ejemplos', 'facturas_emitidas_docs',
                    'firma_solicitudes'
                  )
                """
            ).fetchall()
        }
        objetos = self.conn.execute(
            """
            SELECT
              to_regclass('public.usuarios_permisos_globales') AS tabla_permisos,
              to_regclass('public.idx_usuarios_permisos_globales_usuario') AS indice_permisos,
              to_regclass('public.dgt_facturas') AS tabla_dgt_facturas,
              to_regclass('public.idx_dgt_facturas_factura') AS indice_dgt_facturas,
              to_regclass('public.comunicaciones_avisos_estado') AS tabla_avisos_correo,
              to_regclass('public.comunicaciones_avisos_vistos') AS tabla_avisos_vistos,
              to_regclass('public.categorias_documentales') AS tabla_categorias_documentales,
              to_regclass('public.documentos_archivo') AS tabla_documentos_archivo,
              to_regclass('public.comunicaciones_adjuntos_decisiones') AS tabla_decisiones_adjuntos,
              to_regclass('public.firma_solicitudes') AS tabla_firma_solicitudes,
              to_regclass('public.idx_firma_solicitudes_empresa') AS indice_firma_solicitudes,
              to_regclass('public.firma_firmantes') AS tabla_firma_firmantes,
              to_regclass('public.firma_zonas') AS tabla_firma_zonas,
              to_regclass('public.firma_eventos') AS tabla_firma_eventos,
              to_regclass('public.ocr_aprendizaje_ejemplos') AS tabla_ocr_aprendizaje,
              to_regclass('public.idx_ocr_aprendizaje_empresa') AS indice_ocr_aprendizaje
            """
        ).fetchone()
        tabla_permisos_existe = bool(objetos and objetos["tabla_permisos"])
        indice_permisos_existe = bool(objetos and objetos["indice_permisos"])
        tabla_dgt_facturas_existe = bool(objetos and objetos["tabla_dgt_facturas"])
        indice_dgt_facturas_existe = bool(objetos and objetos["indice_dgt_facturas"])
        tabla_avisos_correo_existe = bool(
            objetos and objetos.get("tabla_avisos_correo")
        )
        tabla_avisos_vistos_existe = bool(
            objetos and objetos.get("tabla_avisos_vistos")
        )
        tabla_categorias_existe = bool(objetos and objetos.get("tabla_categorias_documentales"))
        tabla_documentos_existe = bool(objetos and objetos.get("tabla_documentos_archivo"))
        tabla_decisiones_existe = bool(objetos and objetos.get("tabla_decisiones_adjuntos"))
        tabla_firma_solicitudes_existe = bool(objetos and objetos.get("tabla_firma_solicitudes"))
        indice_firma_solicitudes_existe = bool(objetos and objetos.get("indice_firma_solicitudes"))
        tabla_firma_firmantes_existe = bool(objetos and objetos.get("tabla_firma_firmantes"))
        tabla_firma_zonas_existe = bool(objetos and objetos.get("tabla_firma_zonas"))
        tabla_firma_eventos_existe = bool(objetos and objetos.get("tabla_firma_eventos"))
        tabla_ocr_aprendizaje_existe = bool(objetos and objetos.get("tabla_ocr_aprendizaje"))
        indice_ocr_aprendizaje_existe = bool(objetos and objetos.get("indice_ocr_aprendizaje"))
        tablas_faltantes = {
            tabla
            for tabla, existe in (
                ("firma_solicitudes", tabla_firma_solicitudes_existe),
                ("ocr_aprendizaje_ejemplos", tabla_ocr_aprendizaje_existe),
            )
            if not existe
        }
        faltantes = [
            (tabla, columna, tipo)
            for tabla, columna, tipo in columnas
            if (tabla, columna) not in existentes and tabla not in tablas_faltantes
        ]

        if (
            not faltantes
            and tabla_permisos_existe
            and indice_permisos_existe
            and tabla_dgt_facturas_existe
            and indice_dgt_facturas_existe
            and tabla_avisos_correo_existe
            and tabla_avisos_vistos_existe
            and tabla_categorias_existe
            and tabla_documentos_existe
            and tabla_decisiones_existe
            and tabla_firma_solicitudes_existe
            and indice_firma_solicitudes_existe
            and tabla_firma_firmantes_existe
            and tabla_firma_zonas_existe
            and tabla_firma_eventos_existe
            and tabla_ocr_aprendizaje_existe
            and indice_ocr_aprendizaje_existe
        ):
            self._seed_categorias_documentales()
            self.conn.commit()
            return

        if not tabla_firma_solicitudes_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS firma_solicitudes (
                  id TEXT PRIMARY KEY, codigo_empresa TEXT NOT NULL, ejercicio INTEGER NOT NULL,
                  origen TEXT NOT NULL DEFAULT 'archivo', documento_archivo_id TEXT,
                  nombre_documento TEXT NOT NULL, ruta_origen TEXT NOT NULL, ruta_envio TEXT,
                  hash_origen TEXT NOT NULL, proveedor TEXT NOT NULL DEFAULT 'signrequest',
                  request_id TEXT, external_id TEXT, asunto TEXT, mensaje TEXT,
                  usar_sms INTEGER NOT NULL DEFAULT 0, estado TEXT NOT NULL DEFAULT 'borrador',
                  ruta_firmado TEXT, ruta_registro_firma TEXT, sha256_firmado TEXT,
                  sha256_registro_firma TEXT, security_hash TEXT, signing_log_security_hash TEXT,
                  documento_firmado_archivo_id TEXT, creado_por TEXT, created_at TEXT NOT NULL,
                  updated_at TEXT NOT NULL, enviado_at TEXT, firmado_at TEXT,
                  UNIQUE(proveedor, request_id)
                )
                """
            )
        if not indice_firma_solicitudes_existe:
            self.conn.execute(
                """CREATE INDEX IF NOT EXISTS idx_firma_solicitudes_empresa
                ON firma_solicitudes(codigo_empresa, ejercicio, estado, created_at DESC)"""
            )
        if not tabla_firma_firmantes_existe:
            self.conn.execute(
                """CREATE TABLE IF NOT EXISTS firma_firmantes (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  solicitud_id TEXT NOT NULL, orden INTEGER NOT NULL DEFAULT 1,
                  nombre TEXT, email TEXT NOT NULL, telefono TEXT, tercero_id TEXT,
                  es_remitente INTEGER NOT NULL DEFAULT 0, estado TEXT NOT NULL DEFAULT 'pendiente'
                )"""
            )
        if not tabla_firma_zonas_existe:
            self.conn.execute(
                """CREATE TABLE IF NOT EXISTS firma_zonas (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  solicitud_id TEXT NOT NULL, pagina INTEGER NOT NULL,
                  x DOUBLE PRECISION NOT NULL, y DOUBLE PRECISION NOT NULL,
                  ancho DOUBLE PRECISION NOT NULL, alto DOUBLE PRECISION NOT NULL,
                  firmante INTEGER NOT NULL
                )"""
            )
        if not tabla_firma_eventos_existe:
            self.conn.execute(
                """CREATE TABLE IF NOT EXISTS firma_eventos (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  solicitud_id TEXT NOT NULL, tipo TEXT NOT NULL, detalle_json TEXT,
                  usuario TEXT, created_at TEXT NOT NULL
                )"""
            )
        if not tabla_ocr_aprendizaje_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS ocr_aprendizaje_ejemplos (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  empresa_id TEXT NOT NULL,
                  documento_id TEXT NOT NULL,
                  factura_id TEXT NOT NULL UNIQUE,
                  proveedor_nif TEXT,
                  origen_path TEXT,
                  datos_validados_json TEXT NOT NULL,
                  estado TEXT NOT NULL DEFAULT 'pendiente',
                  modelo_destino TEXT,
                  fecha_validacion TEXT NOT NULL,
                  fecha_exportacion TEXT,
                  notas TEXT,
                  marcas_json TEXT NOT NULL DEFAULT '{}'
                )
                """
            )
        if not indice_ocr_aprendizaje_existe:
            self.conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_ocr_aprendizaje_empresa "
                "ON ocr_aprendizaje_ejemplos(empresa_id, estado, proveedor_nif)"
            )

        for tabla, columna, tipo in faltantes:
            self.conn.execute(
                f"ALTER TABLE {tabla} ADD COLUMN IF NOT EXISTS {columna} {tipo}"
            )
        if not tabla_permisos_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS usuarios_permisos_globales (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  usuario_id INTEGER NOT NULL,
                  permiso TEXT NOT NULL,
                  activo INTEGER NOT NULL DEFAULT 1,
                  created_at TEXT NOT NULL,
                  updated_at TEXT NOT NULL,
                  UNIQUE(usuario_id, permiso)
                )
                """
            )
        if not indice_permisos_existe:
            self.conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_usuarios_permisos_globales_usuario "
                "ON usuarios_permisos_globales(usuario_id)"
            )
        if not tabla_dgt_facturas_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS dgt_facturas (
                  expediente_id TEXT PRIMARY KEY,
                  factura_id TEXT NOT NULL UNIQUE,
                  codigo_empresa TEXT NOT NULL,
                  ejercicio INTEGER NOT NULL,
                  destinatario TEXT NOT NULL,
                  honorarios DOUBLE PRECISION NOT NULL DEFAULT 0,
                  tasa_dgt DOUBLE PRECISION NOT NULL DEFAULT 0,
                  impuesto_620 DOUBLE PRECISION NOT NULL DEFAULT 0,
                  otros_suplidos DOUBLE PRECISION NOT NULL DEFAULT 0,
                  created_at TEXT NOT NULL,
                  updated_at TEXT NOT NULL
                )
                """
            )
        if not indice_dgt_facturas_existe:
            self.conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_dgt_facturas_factura "
                "ON dgt_facturas(factura_id)"
            )
        if not tabla_avisos_correo_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS comunicaciones_avisos_estado (
                  usuario_id INTEGER PRIMARY KEY,
                  ultimo_control_at TEXT NOT NULL,
                  updated_at TEXT NOT NULL
                )
                """
            )
        if not tabla_avisos_vistos_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS comunicaciones_avisos_vistos (
                  usuario_id INTEGER NOT NULL,
                  graph_message_id TEXT NOT NULL,
                  avisado_at TEXT NOT NULL,
                  PRIMARY KEY (usuario_id, graph_message_id)
                )
                """
            )
        if not tabla_categorias_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS categorias_documentales (
                  id TEXT PRIMARY KEY,nombre TEXT NOT NULL,
                  carpeta TEXT NOT NULL UNIQUE,permite_ocr INTEGER NOT NULL DEFAULT 0,
                  activa INTEGER NOT NULL DEFAULT 1,orden INTEGER NOT NULL DEFAULT 0
                )
                """
            )
        if not tabla_documentos_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS documentos_archivo (
                  id TEXT PRIMARY KEY,codigo_empresa TEXT NOT NULL,ejercicio INTEGER NOT NULL,
                  categoria_id TEXT NOT NULL,nombre_original TEXT NOT NULL,
                  nombre_archivo TEXT NOT NULL,ruta TEXT NOT NULL,hash_archivo TEXT NOT NULL,
                  tamano INTEGER,mime_type TEXT,origen TEXT NOT NULL DEFAULT 'correo',
                  comunicacion_id TEXT,mensaje_id TEXT,graph_message_id TEXT,
                  graph_attachment_id TEXT,correo_remitente TEXT,correo_asunto TEXT,
                  estado TEXT NOT NULL DEFAULT 'archivado',ocr_documento_id TEXT,
                  creado_por TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,
                  UNIQUE(codigo_empresa,hash_archivo)
                )
                """
            )
            self.conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_documentos_archivo_empresa "
                "ON documentos_archivo(codigo_empresa,ejercicio,categoria_id,created_at DESC)"
            )
        if not tabla_decisiones_existe:
            self.conn.execute(
                """
                CREATE TABLE IF NOT EXISTS comunicaciones_adjuntos_decisiones (
                  graph_message_id TEXT NOT NULL,graph_attachment_id TEXT NOT NULL,
                  nombre TEXT,accion TEXT NOT NULL,categoria_id TEXT,documento_id TEXT,
                  created_at TEXT NOT NULL,
                  PRIMARY KEY(graph_message_id,graph_attachment_id)
                )
                """
            )
        self._seed_categorias_documentales()
        self.conn.commit()

    def _asegurar_esquema_mensajeria_local(self) -> None:
        row = self.conn.execute(
            "SELECT to_regclass('public.mensajeria_adjuntos_entrada') AS tabla"
        ).fetchone()
        # Dobles de prueba/diagnostico antiguos pueden no exponer esta consulta.
        if row is None or "tabla" not in row:
            return
        if row is not None and row.get("tabla"):
            return
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS mensajeria_adjuntos_entrada (
              id TEXT PRIMARY KEY,mensaje_remoto_id TEXT NOT NULL,
              conversacion_remota_id TEXT NOT NULL,codigo_empresa TEXT NOT NULL,
              empresa_nombre TEXT,nombre_original TEXT NOT NULL,ruta_entrada TEXT NOT NULL,
              hash_archivo TEXT NOT NULL,tamano INTEGER,mime_type TEXT,remitente TEXT,
              estado TEXT NOT NULL DEFAULT 'pendiente_clasificar',error_detalle TEXT,
              documento_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL
            )
            """
        )
        self.conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_msg_adjuntos_entrada_estado "
            "ON mensajeria_adjuntos_entrada(estado,codigo_empresa,created_at)"
        )
        self.conn.commit()

    def _asegurar_esquema_plantillas_firma(self) -> None:
        nombres = (
            "plantillas_firma", "plantillas_firma_empresas", "plantillas_firma_campos",
            "plantillas_firma_firmantes", "plantillas_firma_zonas", "documentos_firma_generados",
        )
        row = self.conn.execute(
            "SELECT " + ",".join(f"to_regclass('public.{nombre}') AS {nombre}" for nombre in nombres)
        ).fetchone()
        # Algunos adaptadores de diagnostico antiguos no exponen esta consulta;
        # en una conexion PostgreSQL real siempre devuelve una fila.
        if row is None:
            return
        tablas_completas = bool(row and all(row.get(nombre) for nombre in nombres))
        if not tablas_completas:
            self.conn.executescript(
                """
            CREATE TABLE IF NOT EXISTS plantillas_firma (
              id TEXT PRIMARY KEY,nombre TEXT NOT NULL UNIQUE,descripcion TEXT,
              archivo_relativo TEXT NOT NULL UNIQUE,alcance TEXT NOT NULL DEFAULT 'global',
              version INTEGER NOT NULL DEFAULT 1,hash_docx TEXT NOT NULL,asunto TEXT,mensaje TEXT,
              activa INTEGER NOT NULL DEFAULT 0,zonas_revisadas INTEGER NOT NULL DEFAULT 0,
              creado_por TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS plantillas_firma_empresas (
              plantilla_id TEXT NOT NULL REFERENCES plantillas_firma(id) ON DELETE CASCADE,
              codigo_empresa TEXT NOT NULL,PRIMARY KEY(plantilla_id,codigo_empresa)
            );
            CREATE TABLE IF NOT EXISTS plantillas_firma_campos (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              plantilla_id TEXT NOT NULL REFERENCES plantillas_firma(id) ON DELETE CASCADE,
              clave TEXT NOT NULL,etiqueta TEXT NOT NULL,origen TEXT NOT NULL DEFAULT 'manual',
              campo_origen TEXT,tipo TEXT NOT NULL DEFAULT 'texto',obligatorio INTEGER NOT NULL DEFAULT 0,
              valor_defecto TEXT,orden INTEGER NOT NULL DEFAULT 0,UNIQUE(plantilla_id,clave)
            );
            CREATE TABLE IF NOT EXISTS plantillas_firma_firmantes (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              plantilla_id TEXT NOT NULL REFERENCES plantillas_firma(id) ON DELETE CASCADE,
              rol TEXT NOT NULL,origen TEXT NOT NULL DEFAULT 'manual',nombre TEXT,email TEXT,telefono TEXT,
              orden INTEGER NOT NULL DEFAULT 1,
              usar_sms INTEGER NOT NULL DEFAULT 0,UNIQUE(plantilla_id,orden)
            );
            CREATE TABLE IF NOT EXISTS plantillas_firma_zonas (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              plantilla_id TEXT NOT NULL REFERENCES plantillas_firma(id) ON DELETE CASCADE,
              rol TEXT NOT NULL,pagina INTEGER NOT NULL,x DOUBLE PRECISION NOT NULL,
              y DOUBLE PRECISION NOT NULL,ancho DOUBLE PRECISION NOT NULL,alto DOUBLE PRECISION NOT NULL
            );
            CREATE TABLE IF NOT EXISTS documentos_firma_generados (
              id TEXT PRIMARY KEY,plantilla_id TEXT NOT NULL REFERENCES plantillas_firma(id) ON DELETE RESTRICT,
              plantilla_version INTEGER NOT NULL,plantilla_hash TEXT NOT NULL,codigo_empresa TEXT,
              tercero_id TEXT,titulo TEXT NOT NULL,datos_json TEXT NOT NULL,firmantes_json TEXT NOT NULL,
              ruta_docx TEXT NOT NULL,ruta_pdf TEXT NOT NULL,hash_docx TEXT,hash_pdf TEXT,
              estado TEXT NOT NULL DEFAULT 'borrador',solicitud_id TEXT UNIQUE,creado_por TEXT,
              created_at TEXT NOT NULL,updated_at TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_documentos_firma_generados
              ON documentos_firma_generados(codigo_empresa,created_at DESC);
                """
            )
        columnas = self.conn.execute(
            """SELECT column_name FROM information_schema.columns
            WHERE table_schema=current_schema() AND table_name='plantillas_firma_firmantes'"""
        ).fetchall()
        existentes = {str(item["column_name"]) for item in columnas}
        for nombre in ("nombre", "email", "telefono"):
            if nombre not in existentes:
                self.conn.execute(
                    f"ALTER TABLE plantillas_firma_firmantes ADD COLUMN IF NOT EXISTS {nombre} TEXT"
                )
        if not tablas_completas or any(nombre not in existentes for nombre in ("nombre", "email", "telefono")):
            self.conn.commit()
