"""Migracion verificable de una base SQLite de Gest2A3Eco a PostgreSQL.

Este modulo no modifica el fichero SQLite de origen. Se usa para crear una
copia de validacion en PostgreSQL antes de activar el nuevo motor en la UI.
"""

from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


class MigracionPostgresError(RuntimeError):
    """Error controlado durante la preparacion o validacion de la migracion."""


@dataclass(frozen=True)
class ResultadoMigracionPostgres:
    tablas: int
    filas: int
    filas_por_tabla: dict[str, int]


@dataclass(frozen=True)
class ResultadoValidacionPostgres:
    filas_por_tabla: dict[str, tuple[int, int]]

    @property
    def diferencias(self) -> dict[str, tuple[int, int]]:
        return {
            tabla: conteos
            for tabla, conteos in self.filas_por_tabla.items()
            if conteos[0] != conteos[1]
        }


def _identificador(nombre: str) -> str:
    """Devuelve un identificador SQL entrecomillado y seguro."""
    return '"' + str(nombre).replace('"', '""') + '"'


def _tipo_postgres(tipo_sqlite: str) -> str:
    tipo = str(tipo_sqlite or "").upper()
    if "INT" in tipo:
        return "INTEGER"
    if any(token in tipo for token in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in tipo:
        return "BYTEA"
    if any(token in tipo for token in ("NUMERIC", "DECIMAL", "BOOL", "DATE", "TIME")):
        return tipo
    return "TEXT"


def _tablas_origen(conn: sqlite3.Connection) -> list[str]:
    return [
        row[0]
        for row in conn.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall()
    ]


def _definicion_tabla(conn: sqlite3.Connection, tabla: str) -> tuple[str, list[str], list[str]]:
    filas = conn.execute(f"PRAGMA table_info({_identificador(tabla)})").fetchall()
    if not filas:
        raise MigracionPostgresError(f"No se pudo leer la definicion de la tabla {tabla}.")

    ddl_origen_row = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (tabla,)
    ).fetchone()
    ddl_origen = str(ddl_origen_row[0] or "") if ddl_origen_row else ""
    autoincrementales = {
        match.group(1).lower()
        for match in re.finditer(
            r'"?([A-Za-z_][A-Za-z0-9_]*)"?\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT',
            ddl_origen,
            flags=re.IGNORECASE,
        )
    }

    columnas: list[str] = []
    nombres: list[str] = []
    clave_primaria: list[tuple[int, str]] = []
    for _, nombre, tipo, obligatorio, defecto, orden_pk in filas:
        nombre = str(nombre)
        nombres.append(nombre)
        partes = [_identificador(nombre)]
        if nombre.lower() in autoincrementales:
            partes.append("INTEGER GENERATED BY DEFAULT AS IDENTITY")
        else:
            partes.append(_tipo_postgres(str(tipo)))
        if defecto is not None:
            partes.extend(("DEFAULT", str(defecto)))
        if obligatorio:
            partes.append("NOT NULL")
        columnas.append(" ".join(partes))
        if orden_pk:
            clave_primaria.append((int(orden_pk), nombre))

    if clave_primaria:
        pk = ", ".join(_identificador(nombre) for _, nombre in sorted(clave_primaria))
        columnas.append(f"PRIMARY KEY ({pk})")
    ddl = f"CREATE TABLE {_identificador(tabla)} (\n  " + ",\n  ".join(columnas) + "\n)"
    return ddl, nombres, [nombre for _, nombre in sorted(clave_primaria)]


def _indices_unicos(conn: sqlite3.Connection, tabla: str) -> Iterable[tuple[str, list[str], str]]:
    for _, nombre, unico, origen, _ in conn.execute(f"PRAGMA index_list({_identificador(tabla)})").fetchall():
        if not unico or origen == "pk":
            continue
        columnas = [row[2] for row in conn.execute(f"PRAGMA index_info({_identificador(nombre)})").fetchall()]
        if columnas:
            definicion = conn.execute(
                "SELECT sql FROM sqlite_master WHERE type='index' AND name=?",
                (nombre,),
            ).fetchone()
            condicion = ""
            if definicion and definicion[0]:
                match = re.search(r"\bWHERE\b(.+)$", str(definicion[0]), flags=re.IGNORECASE | re.DOTALL)
                if match:
                    condicion = match.group(1).strip()
            yield str(nombre), [str(columna) for columna in columnas], condicion


def _normalizar_fila_origen(row: sqlite3.Row, tipos: dict[str, str]) -> tuple:
    """Normaliza permisividad de SQLite antes de enviar valores a PostgreSQL.

    SQLite puede almacenar la cadena vacia en una columna INTEGER o REAL. En
    PostgreSQL ese valor no es valido; en datos historicos representa ausencia
    de dato y se convierte a NULL.
    """
    valores = []
    for nombre in row.keys():
        valor = row[nombre]
        tipo = _tipo_postgres(tipos.get(nombre, ""))
        if isinstance(valor, str) and not valor.strip() and tipo in {
            "INTEGER", "DOUBLE PRECISION", "NUMERIC", "DECIMAL", "BOOL"
        }:
            valores.append(None)
        elif isinstance(valor, str) and "\x00" in valor:
            # SQLite admite NUL embebidos en TEXT; PostgreSQL los rechaza.
            # Los OCR historicos pueden contenerlos como ruido de extraccion.
            valores.append(valor.replace("\x00", ""))
        else:
            valores.append(valor)
    return tuple(valores)


def migrar_sqlite_a_postgres(
    sqlite_path: str | Path,
    postgres_dsn: str,
    *,
    lote: int = 500,
) -> ResultadoMigracionPostgres:
    """Copia las tablas y datos de SQLite a una base PostgreSQL vacia.

    Las claves foraneas no se materializan aun: se validan y se incorporaran
    con el gestor PostgreSQL. Esto permite importar el legado aunque contenga
    referencias historicas incompletas.
    """
    if lote < 1:
        raise ValueError("El tamano de lote debe ser positivo.")
    origen_path = Path(sqlite_path)
    if not origen_path.is_file():
        raise FileNotFoundError(f"No existe la base SQLite de origen: {origen_path}")

    try:
        import psycopg
    except ImportError as exc:
        raise MigracionPostgresError(
            "Falta la dependencia psycopg. Ejecuta: pip install -r requirements.txt"
        ) from exc

    origen = sqlite3.connect(f"file:{origen_path.as_posix()}?mode=ro", uri=True)
    origen.row_factory = sqlite3.Row
    try:
        tablas = _tablas_origen(origen)
        filas_por_tabla: dict[str, int] = {}
        tabla_actual = ""
        with psycopg.connect(postgres_dsn) as destino:
            with destino.cursor() as cur:
                for tabla in tablas:
                    tabla_actual = tabla
                    ddl, columnas, _ = _definicion_tabla(origen, tabla)
                    tipos = {
                        str(row[1]): str(row[2])
                        for row in origen.execute(f"PRAGMA table_info({_identificador(tabla)})").fetchall()
                    }
                    cur.execute(ddl)
                    columnas_sql = ", ".join(_identificador(columna) for columna in columnas)
                    valores_sql = ", ".join("%s" for _ in columnas)
                    insert_sql = f"INSERT INTO {_identificador(tabla)} ({columnas_sql}) VALUES ({valores_sql})"
                    lector = origen.execute(f"SELECT {columnas_sql} FROM {_identificador(tabla)}")
                    total = 0
                    while rows := lector.fetchmany(lote):
                        cur.executemany(
                            insert_sql,
                            [_normalizar_fila_origen(row, tipos) for row in rows],
                        )
                        total += len(rows)
                    filas_por_tabla[tabla] = total
                    for indice, columnas_indice, condicion in _indices_unicos(origen, tabla):
                        cols = ", ".join(_identificador(columna) for columna in columnas_indice)
                        where_sql = f" WHERE {condicion}" if condicion else ""
                        cur.execute(
                            f"CREATE UNIQUE INDEX {_identificador(indice)} "
                            f"ON {_identificador(tabla)} ({cols}){where_sql}"
                        )
                    if "id" in columnas:
                        cur.execute(
                            "SELECT pg_get_serial_sequence(%s, %s)", (tabla, "id")
                        )
                        secuencia = cur.fetchone()[0]
                        if secuencia:
                            cur.execute(
                                f"SELECT setval(%s, COALESCE(MAX({_identificador('id')}), 1), "
                                f"MAX({_identificador('id')}) IS NOT NULL) FROM {_identificador(tabla)}",
                                (secuencia,),
                            )
        return ResultadoMigracionPostgres(len(tablas), sum(filas_por_tabla.values()), filas_por_tabla)
    except Exception as exc:
        contexto = f" en la tabla {tabla_actual}" if "tabla_actual" in locals() and tabla_actual else ""
        raise MigracionPostgresError(f"La migracion SQLite a PostgreSQL ha fallado{contexto}: {exc}") from exc
    finally:
        origen.close()


def validar_sqlite_contra_postgres(
    sqlite_path: str | Path,
    postgres_dsn: str,
) -> ResultadoValidacionPostgres:
    """Compara el numero de filas de cada tabla sin modificar ninguna base."""
    try:
        import psycopg
    except ImportError as exc:
        raise MigracionPostgresError(
            "Falta la dependencia psycopg. Ejecuta: pip install -r requirements.txt"
        ) from exc

    origen_path = Path(sqlite_path)
    if not origen_path.is_file():
        raise FileNotFoundError(f"No existe la base SQLite de origen: {origen_path}")
    origen = sqlite3.connect(f"file:{origen_path.as_posix()}?mode=ro", uri=True)
    try:
        resultado: dict[str, tuple[int, int]] = {}
        with psycopg.connect(postgres_dsn) as destino:
            with destino.cursor() as cur:
                for tabla in _tablas_origen(origen):
                    origen_total = int(origen.execute(f"SELECT COUNT(*) FROM {_identificador(tabla)}").fetchone()[0])
                    cur.execute(f"SELECT COUNT(*) FROM {_identificador(tabla)}")
                    destino_total = int(cur.fetchone()[0])
                    resultado[tabla] = (origen_total, destino_total)
        return ResultadoValidacionPostgres(resultado)
    except Exception as exc:
        raise MigracionPostgresError(f"La validacion SQLite/PostgreSQL ha fallado: {exc}") from exc
    finally:
        origen.close()
